# Generated by Django 5.1.6 on 2025-02-19 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationName', models.CharField(max_length=100)),
                ('locationType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.locationtype')),
            ],
        ),
    ]
