# Generated by Django 5.1.4 on 2025-02-24 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_batch_part_inventoryrecord_batch_part'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryTransactionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('duration', models.FloatField()),
                ('timeStamp', models.DateField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.batch')),
                ('fromLocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromLocation', to='inventory.location')),
                ('toLocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toLocation', to='inventory.location')),
                ('statusId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventorytransactionstatus')),
            ],
        ),
    ]
