# Generated by Django 5.1.4 on 2025-02-24 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_inventorytransactionstatus_inventorytransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batchNumber',
            field=models.CharField(max_length=100),
        ),
    ]
