# Generated by Django 5.1.4 on 2025-02-25 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_batch_batchnumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batch',
            old_name='part',
            new_name='partNumber',
        ),
    ]
