# Generated by Django 5.1.4 on 2025-02-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_rename_part_batch_partnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='partNumber',
            field=models.CharField(max_length=100),
        ),
    ]
