# Generated by Django 5.1.4 on 2025-02-25 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_part_partnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='quantity',
        ),
    ]
