# Generated by Django 5.1.4 on 2025-02-25 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_remove_batch_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytransaction',
            name='duration',
            field=models.FloatField(null=True),
        ),
    ]
